
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_galaxy_covid_demo'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'sandbox-galaxy'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_modules"
    - "logs"

# configure all the models in my project
models:
  dbt_galaxy_covid_demo:
    +materialized: table
    +on_table_exists: drop

seeds:
  dbt_galaxy_covid_demo:
    snowflake_databank_demographics:
      database: "dbt_aws_src"
      schema: "snow"

    snowflake_owid_vaccinations:
      database: "dbt_aws_src"
      schema: "snow"
      config:
        column_types:
          DAILY_VACCINATIONS_RAW: long


# override some 'dbt_utils' macros with Trino-SQL versions
# so that the 'date_spine' macro can work on Trino
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['trino_utils', 'dbt_utils']
