with renamed as (

select
    id                              as listing_id,
    listing_url                     as listing_url,
    to_date(last_scraped)           as last_retrieval_date,
    name                            as listing_name,
    description                     as listing_description,
    neighborhood_overview           as neighborhood_overview,
    picture_url                     as picture_url,
    host_id                         as host_id,
    host_url                        as host_url,
    to_date(host_since)             as host_since_date,
    host_location                   as host_location,
    host_about                      as host_about,
    host_response_time              as host_response_time,
    host_response_rate              as host_response_rate,
    host_acceptance_rate            as host_acceptance_rate,
    host_is_superhost               as host_is_superhost,
    host_thumbnail_url              as host_thumbnail_url,
    host_neighbourhood              as host_neighborhood,
    -- host_listings_count,
    -- host_total_listings_count,
    host_verifications              as host_verifications,
    boolean(host_has_profile_pic)   as host_has_profile_pic,
    boolean(host_identity_verified) as host_is_verified,
    neighbourhood                   as neighborhood,
    neighbourhood_cleansed          as neighborhood_cleansed,
    latitude                        as latitude,
    longitude                       as longitude,
    property_type                   as property_type,
    room_type                       as room_type,
    accommodates                    as accommodates,
    bathrooms                       as num_bathrooms,
    bathrooms_text                  as bathrooms_text,
    beds                            as num_beds,
    amenities                       as amenities,
    price                           as price,
    minimum_nights                  as minimum_nights,
    maximum_nights                  as maximum_nights,
    minimum_minimum_nights          as minimum_minimum_nights,
    maximum_minimum_nights          as maximum_minimum_nights,
    minimum_maximum_nights          as minimum_maximum_nights,
    maximum_maximum_nights          as maximum_maximum_nights,
    minimum_nights_avg_ntm          as minimum_nights_avg_ntm,
    maximum_nights_avg_ntm          as maximum_nights_avg_ntm,
    calendar_updated                as calendar_updated,
    has_availability                as has_availability,
    availability_30                 as availability_30,
    availability_60                 as availability_60,
    availability_90                 as availability_90,
    availability_365                as availability_365,
    calendar_last_scraped           as days_since_last_calendar_scrape,
    -- number_of_reviews,              
    -- number_of_reviews_ltm,
    -- number_of_reviews_l30d,
    -- first_review,
    -- last_review,
    review_scores_rating            as review_scores_rating,
    review_scores_accuracy          as review_scores_accuracy,
    review_scores_cleanliness       as review_scores_cleanliness,
    review_scores_checkin           as review_scores_checkin,
    review_scores_communication     as review_scores_communication,
    review_scores_location          as review_scores_location,
    review_scores_value             as review_scores_value,
    license                         as license,
    boolean(instant_bookable)       as is_instant_bookable,
    calculated_host_listings_count  as calculated_host_listings_count,
    calculated_host_listings_count_entire_homes as calculated_host_listings_count_entire_homes,
    calculated_host_listings_count_private_rooms as calculated_host_listings_count_private_rooms,
    calculated_host_listings_count_shared_rooms as calculated_host_listings_count_shared_rooms,
    reviews_per_month               as reviews_per_month
from {{ source('airbnb','listings') }}

)

select * from renamed